const tableData = [
  {
    projectId: "101",
    status: "Active",
    region: "North",
    type: "TypeA",
    feature: "Feature1",
    toggleActive: true,
  },
  {
    projectId: "102",
    status: "Inactive",
    region: "South",
    type: "TypeB",
    feature: "Feature2",
    toggleActive: false,
  },
  {
    projectId: "103",
    status: "Pending",
    region: "East",
    type: "TypeA",
    feature: "Feature1",
    toggleActive: true,
  },
  {
    projectId: "104",
    status: "Active",
    region: "West",
    type: "TypeB",
    feature: "Feature2",
    toggleActive: false,
  },
  {
    projectId: "105",
    status: "Inactive",
    region: "North",
    type: "TypeA",
    feature: "Feature1",
    toggleActive: false,
  },
  {
    projectId: "106",
    status: "Pending",
    region: "South",
    type: "TypeB",
    feature: "Feature2",
    toggleActive: true,
  },
  {
    projectId: "107",
    status: "Active",
    region: "East",
    type: "TypeA",
    feature: "Feature2",
    toggleActive: true,
  },
  {
    projectId: "108",
    status: "Inactive",
    region: "West",
    type: "TypeB",
    feature: "Feature1",
    toggleActive: false,
  },
];
